# -*- coding: utf-8 -*-
"""Linear Algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SxhHrKihNv-DC9Kwy4xoAB83791hrirw
"""

import numpy as np

A = np.array([[6,4,8],[4,5,9],[7,5,3]])
print("print rank of A",np.linalg.matrix_rank(A))
print("trance A",np.trace(A))
print("Determinant of A", np.linalg.det(A))
print("Invert",np.linalg.inv(A))
print("matrix",np.linalg.matrix_power(A,3))

from numpy import linalg as lg
a=np.array([[1,-2j],[3,4j]])
print("array is",a)

c,d = lg.eigh(a)
print("value of C",c)
print("value of D",c)

a = np.diag((1,2,3))
print("a=", a)
c,d =lg.eig(a)
print("c= ",c)
print("d=",d)

p= np.dot(5,6)
print("dot of p", p)

v1= 2+3j
v2= 9+7j
p=np.dot(v1,v2)
print("dot of v1 & v2",p )

p=np.vdot(v1,v2)
print(p)

a=np.array([[1,2],[3,4]])
b=np.array([8,9])
print(("solution of linear equation:",np.linalg.solve(a,b)))

import numpy as np
import matplotlib.pyplot as plt
x= np.arange(0,9)
a=np.array([x, np.ones(9)])
y=[1,2,5,8,4,7,9,6,12.02]
w= np.linalg.lstsq(a.T,y)[0]
line = w[0]*x+w[1]
plt.plot(x,line,'r-')
plt.plot(x,y,'o')
plt.show()

a=np.array([[10255,255896,95875451],[54578445,2656865,264545],[26656,264598556,-154854]])
print(("Determinant",np.linalg.det(a)))

a=np.array([[10255,255896,95875451],[54578445,2656865,264545],[26656,264598556,-154854]])
print("Trance",np.trace(a))

