# -*- coding: utf-8 -*-
"""Vector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TXMoz9Psu28-J4Szftx3rEvRHlUcdaCN
"""

# Dot product 
import time 
import numpy 
import array 
a= array.array('q')
for i in range(10000000):
  a.append(i);
b=array.array('q')
for i in range(10000000,20000000):
  b.append(i)

tic = time.process_time()
dot = 0.0;

for i in range(len(a)):
  dot += a[i]*b[i]

toc = time.process_time()
print("dot_product ="+str(dot));
print("computation time ="+str(1000*(toc-tic))+"ms")

nt= time.process_time()
n_dot_product= numpy.dot(a,b) #dot product 
n_toc= time.process_time()
print("\n n_dot_product="+str(n_dot_product))
print("\ncomputation time="+str(1000*(n_toc - nt))+"ms")

# outer product
import time 
import numpy
import array
a= array.array('i')
for i in range(2000):
  a.append(i);
b=array.array('i')
for i in range(2000,4000):
  b.append(i)
tic = time.process_time()
outer = numpy.zeros((2000,2000))
for i in range(len(a)):
  for j in range(len(b)):
    outer[i][j]=a[i]*b[j]
  
toc = time.process_time()

print("outer product = " +str(outer));
print("computation time= "+str(1000*(toc - tic))+"ms")

nt = time.process_time()
outer_product = numpy.outer(a,b)
n_toc = time.process_time()

print("outer product = "+str(outer_product));
print("\n computation time = "+str(1000*(n_toc - nt ))+'ms')

# Element wise Product 
import time 
import numpy as np
import array
a= array.array('i')
for i in range(500000):
  a.append(i);

b= array.array('i')
for i in range(500000,1000000):
  b.append(i)

vector = numpy.zeros((500000))

tic = time.process_time()
for i in range(len(a)):
  vector[i]=a[i]*b[i]

toc = time.process_time()

print("element wise product = "+str(vector));
print("\n computation time "+str(10000*(toc - tic))+"ms")

